---
- name: Uninstall a Windows App
  hosts: all_windows_hosts_ntlm
  gather_facts: no
  vars:
    app_name: UniversalForwarder
  tasks:
    - name: Find app ProductID
      ansible.windows.win_shell: Get-WmiObject Win32_Product | Where-Object{$_.Name -eq "{{ app_name }}"} | Select-Object -ExpandProperty IdentifyingNumber
      register: productid

    - name: Uninstall the app
      ansible.windows.win_package:
        product_id: "{{ productid['stdout_lines'][0] }}"
        state: absent
